### ISSUE TITLE
Canvaspop linking problem

### ISSUE THREAD

**Issue by ruminMCFC** [canvaspop/canvaspop-ios-library#6]
Hi everyone....i created demo it's working fine.but i integrate in  my existing app then erorr display like 205 duplicate symbol.when i add framework & run then app then problem occur.

**Comment by karlclement** [comment]
Hey there,

When you imported the `PopUpLib` did you follow this format:

![image](https://cloud.githubusercontent.com/assets/539188/7371996/38830952-ed92-11e4-842e-502a0ab81b3f.png)

**Comment by barfoon** [comment]
Hi @ruminMCFC, we're you able to get this resolved ok?
